= Getting Started with Azure Apps Enterprise

== What is Azure Spring Apps Enterprise

== Why is this learning path important?

Say something here TODO! Use the effective kube debugging to give you hints



== Who is this learning path for?

Say something here TODO!

== Learning outcomes

Say something here TODO!



== VMware Tanzu capabilities present in Azure Spring Apps Enteprise

In addition to the base functionality that comes with Azure Spring Apps, using the Enterprise edition provides quite a bit more functionality.
An instance of an Azure Spring App Enterprise  will have the following capabilities available for you to use.

=== Build Service

Executes reproducible container builds and keeps images up-to-date using kpack, a Cloud Native Buildpacks Platform.

=== Service Registry

Provides a highly available registry for your services to dynamically discover and call other services.

=== Application Configuration Service

Provides centralized configuration with Git integration.

=== Spring Cloud Gateway

Provides dynamic application route configuration and centralized place for security control like SSO.

=== API Portal

View and test out API group defined in Spring Cloud Gateway