
== Prerequisites

This lab *requires* that you have an Azure account which has access to Azure Spring Apps Enterprise.

!!!!!!!!!TODO instructions here on how to see if you have access in the web console.

This lab assumes you know Spring, but you are not that familiar with Azure or Azure Spring Apps Enterprise (ASA-E). If you have limited experience with ASA-E we recommend you read a https://onevmw-my.sharepoint.com/:w:/g/personal/spousty_vmware_com/EZq6t15kvZJEmM11jSrGYI0BNVg2ejUT-x9DRTHAZUOV9w?e=WQkBsF[basic document] basic Azure terminology. If you want to go deeper you can do the https://docs.microsoft.com/en-us/training/courses/az-900t00[course AZ-900T00], especially the last 2 modules.

It is also important to understand that, for Azure Spring Apps, the web interface is primarily read-only. You can do some very basic high-level resource creation but the majority of your work has to happen through either the command line or IDE plugin (https://code.visualstudio.com/docs/azure/extensions[VSCode] and https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij[Intellij]). Due to this architecture, there will not be many web screenshots until we get to features such as monitoring or logging.

If you comfortable doing all your work, except entering your password, in this lab environment then you are finished with the prequisistes. The next section covers what is required to do this lab outside the browser and on your own personal machine.

== Working own your own machine rather than this environment

It is possible to do all the exercises in this lab on your own machine.

There are separate how-to guides for Intellij and VScode that cover how to use the IDE plugins with Azure.

* https://docs.microsoft.com/en-us/azure/spring-apps/how-to-intellij-deploy-apps[Intellij Azure Spring Apps] specific
* https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/[Intellij general Azure usages]
* https://code.visualstudio.com/docs/java/java-spring-apps[VS Code Azure Spring Apps] specific
* https://code.visualstudio.com/docs/azure/extensions[VS Code general Azure usages]

We also assume you have a JVM &gt; version 8 and Maven already installed on your machine. They should already be set up and working in any terminal where you plan to use the Azure CLI.

Finally, we also assume you have logged in Azure from the CLI or IDE. To check with the CLI type in:

[source,shell]
----
$ az account show

----

If you have not logged in you should be prompted to login. If you are logged in, the response should be some JSON that contains your Subscription ID, Name, and other fields.

With those preliminaries out of the way, let's deploy your Spring Application on ASA-E.

== Configure your system and create your work area in Azure Spring Apps

In this module you are only going to create just enough application that you can learn the terminology and basic mechanics of using ASA-E for your applications. In later modules we will go into more depth.

The first step will be to use the CLI to login to Azure. Because Azure web console and auth follow good security practices, you have to use a device code to login.
Use this command:
 `az login --use-device-code`
 https://learn.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login

. ResourceGroup
 `az group create -l westus -n playing1`
 https://learn.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-create

. Spring App Service
 `az spring create -n the-asa-service -g playing1 --sku Enterprise  --enable-gateway --enable-api-portal`
 https://learn.microsoft.com/en-us/cli/azure/spring?view=azure-cli-latest#az-spring-create
 Same as spinning up any service in Azure - in this case we are spinning up resources that know how to host Spring, and other language runtimes.
 Enterprise also makes it possible to add frequently used technology, such as an API portal, to the resources spun up.

This is kinda cool to set the defaults so you don't have to keep entereing it.

[source,shell]
----
az configure --defaults \
    group=${RESOURCE_GROUP} \
    location=${REGION} \
    spring=${SPRING_APPS_SERVICE}
----