apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: asa-e-getting-started
spec:
  title: Getting Started With Azure Spring Apps Enterprise (ASA-E)
  description: Introduction and getting started with ASA-E, an Azure application platform that integrates projects from the Spring ecosystem. Almost seamlessly, move your apps from your laptop to Azure while keeping all the Spring pieces you have integrated into your application. It is a polyglot service that which allows you to focus on the code, and the containerization and deployment are hendled by ASA-E.
  workshop:
    image: ghcr.io/thesteve0/educates-asa-e-image:latest
    files:
    - image:
        url: $(image_repository)/asa-e-getting-started-files:latest
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
