name: Publish Workshop

on:
  push:
    tags:
      - "[0-9]+.[0-9]+"

jobs:
  publish-workshop:
    runs-on: ubuntu-latest

    if: ${{github.repository != 'vmware-tanzu-labs/educates-workshop-templates'}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: vmware-tanzu-labs/educates-github-actions/publish-workshop@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
